// ---------------------------------------------------------------------------
// Theme customizer config — presets + helpers shared by the customizer panel.
// ---------------------------------------------------------------------------

export type SidebarVariant = "inset" | "sidebar" | "floating";
export type SidebarCollapsible = "icon" | "offcanvas";
export type ContentLayout = "centered" | "full";

export type ThemeConfig = {
  accent: string;
  radius: number;
  font: string;
  sidebarVariant: SidebarVariant;
  sidebarCollapsible: SidebarCollapsible;
  contentLayout: ContentLayout;
};

export const defaultConfig: ThemeConfig = {
  accent: "blue",
  radius: 0.65,
  font: "geist",
  sidebarVariant: "floating",
  sidebarCollapsible: "icon",
  contentLayout: "full",
};

export type Accent = {
  key: string;
  label: string;
  swatch: string;
  primary: string | null; // null = use the theme default (mode-aware neutral)
  fg: string;
};

export const accents: Accent[] = [
  { key: "blue", label: "Blue", swatch: "#0085DB", primary: null, fg: "#FFFFFF" },
  { key: "aqua", label: "Aqua", swatch: "#49BEFF", primary: "#0095DA", fg: "#FFFFFF" },
  { key: "purple", label: "Purple", swatch: "#763EBD", primary: "#763EBD", fg: "#FFFFFF" },
  { key: "green", label: "Green", swatch: "#13DEB9", primary: "#0B9E7E", fg: "#FFFFFF" },
  { key: "cyan", label: "Cyan", swatch: "#00BCD4", primary: "#00ACC1", fg: "#FFFFFF" },
  { key: "orange", label: "Orange", swatch: "#FA896B", primary: "#E9703E", fg: "#FFFFFF" },
  { key: "indigo", label: "Indigo", swatch: "#5C6BC0", primary: "#5C6BC0", fg: "#FFFFFF" },
  { key: "rose", label: "Rose", swatch: "#E91E63", primary: "#E91E63", fg: "#FFFFFF" },
];

export const radii = [
  { label: "0", value: 0 },
  { label: "0.3", value: 0.3 },
  { label: "0.5", value: 0.5 },
  { label: "0.65", value: 0.65 },
  { label: "0.75", value: 0.75 },
  { label: "1.0", value: 1 },
];

export type FontOption = { key: string; label: string; stack: string | null };

export const fonts: FontOption[] = [
  { key: "geist", label: "Geist", stack: null },
  {
    key: "system",
    label: "System",
    stack:
      "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },
  {
    key: "serif",
    label: "Serif",
    stack: "ui-serif, Georgia, Cambria, 'Times New Roman', serif",
  },
  {
    key: "mono",
    label: "Mono",
    stack:
      "var(--font-geist-mono), ui-monospace, SFMono-Regular, Menlo, monospace",
  },
];

export const sidebarVariants: { key: SidebarVariant; label: string }[] = [
  { key: "inset", label: "Inset" },
  { key: "sidebar", label: "Sidebar" },
  { key: "floating", label: "Floating" },
];

export const collapsibleModes: { key: SidebarCollapsible; label: string }[] = [
  { key: "icon", label: "Icon" },
  { key: "offcanvas", label: "Off-canvas" },
];

export const contentLayouts: { key: ContentLayout; label: string }[] = [
  { key: "full", label: "Full width" },
  { key: "centered", label: "Centered" },
];

/** Build a copy-pasteable CSS + notes snippet for the current config. */
export function buildThemeCss(config: ThemeConfig): string {
  const accent = accents.find((a) => a.key === config.accent);
  const font = fonts.find((f) => f.key === config.font);
  const lines: string[] = [];
  lines.push("/* OrbynAdmin theme — generated by the customizer. */");
  lines.push(":root {");
  lines.push(`  --radius: ${config.radius}rem;`);
  if (accent?.primary) {
    lines.push(`  --primary: ${accent.primary};`);
    lines.push(`  --primary-foreground: ${accent.fg};`);
    lines.push(`  --ring: ${accent.primary};`);
    lines.push(`  --sidebar-primary: ${accent.primary};`);
    lines.push(`  --sidebar-ring: ${accent.primary};`);
  }
  if (font?.stack) {
    lines.push(`  --font-sans: ${font.stack};`);
  }
  lines.push("}");
  lines.push("");
  lines.push(
    `/* <Sidebar variant="${config.sidebarVariant}" collapsible="${config.sidebarCollapsible}" /> */`
  );
  lines.push(`/* content layout: ${config.contentLayout} */`);
  return lines.join("\n");
}
